#! /bin/sh

#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#
#      	- https://github.com/ArturRomanchenko/dotfiles
#

pgrep -x sxhkd > /dev/null || sxhkd &

# workspaces
bspc monitor -d 1 2 3 4 5 6
#bspc monitor LVDS-1 -d 7 # TODO: multiple monitors

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^1'
bspc rule -a Nitrogen state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Thunar state=floating rectangle=1100x700+410+190 follow=off

# polybar
$HOME/.config/polybar/launch.sh

# wallpaper
nitrogen --restore &

# Dunst
dunst -config $HOME/.config/bspwm/dunstrc &

# fix pointer
xsetroot -cursor_name left_ptr &

# start compositor
picom --config ~/.config/picom/picom.conf &

# autostart
flameshot &